version: '3'
services:
  redis1:
    image: redis:6.0-alpine3.12
    restart: always
    volumes: ['./data:/data']
    ports: ['20001:6379']
    networks:
      - beacon-network
networks:
  beacon-network:
    driver: bridge


