# nginx-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: beacon-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beacon
  template:
    metadata:
      labels:
        app: beacon
    spec:
      containers:
      - name: beacon
        image: dk-reg.mas:5000/beacon-base:2.0
        env:
        - name: env
          value: dev
        ports:
        - containerPort: 8080
